// <auto-generated />
using System;
using AccomodationBookingMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccomodationBookingMVC.Migrations
{
    [DbContext(typeof(AccommodationContext))]
    [Migration("20251120003942_InitialAccommodationMigration")]
    partial class InitialAccommodationMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccomodationBookingMVC.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.PlatformEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("PlatformEmployees");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Premise", b =>
                {
                    b.Property<int>("PremiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PremiseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<bool>("HasRestroom")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PremiseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PremiseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.HasKey("PremiseId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PremiseTypeId");

                    b.ToTable("Premises");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.PremiseType", b =>
                {
                    b.Property<int>("PremiseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PremiseTypeId"));

                    b.Property<string>("TypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PremiseTypeId");

                    b.ToTable("PremiseTypes");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.RentalAgreement", b =>
                {
                    b.Property<long>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AgreementId"));

                    b.Property<DateOnly>("ConclusionDate")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PremiseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RentalEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RentalStartDate")
                        .HasColumnType("date");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AgreementId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PremiseId");

                    b.HasIndex("TenantId");

                    b.ToTable("RentalAgreements");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("AdditionalWishes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PremiseService", b =>
                {
                    b.Property<int>("PremisesPremiseId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesServiceId")
                        .HasColumnType("int");

                    b.HasKey("PremisesPremiseId", "ServicesServiceId");

                    b.HasIndex("ServicesServiceId");

                    b.ToTable("PremiseService");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Premise", b =>
                {
                    b.HasOne("AccomodationBookingMVC.Models.Owner", "Owner")
                        .WithMany("Premises")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccomodationBookingMVC.Models.PremiseType", "PremiseType")
                        .WithMany("Premises")
                        .HasForeignKey("PremiseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PremiseType");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.RentalAgreement", b =>
                {
                    b.HasOne("AccomodationBookingMVC.Models.PlatformEmployee", "Employee")
                        .WithMany("RentalAgreements")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("AccomodationBookingMVC.Models.Premise", "Premise")
                        .WithMany("RentalAgreements")
                        .HasForeignKey("PremiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccomodationBookingMVC.Models.Tenant", "Tenant")
                        .WithMany("RentalAgreements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Premise");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PremiseService", b =>
                {
                    b.HasOne("AccomodationBookingMVC.Models.Premise", null)
                        .WithMany()
                        .HasForeignKey("PremisesPremiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccomodationBookingMVC.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Owner", b =>
                {
                    b.Navigation("Premises");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.PlatformEmployee", b =>
                {
                    b.Navigation("RentalAgreements");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Premise", b =>
                {
                    b.Navigation("RentalAgreements");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.PremiseType", b =>
                {
                    b.Navigation("Premises");
                });

            modelBuilder.Entity("AccomodationBookingMVC.Models.Tenant", b =>
                {
                    b.Navigation("RentalAgreements");
                });
#pragma warning restore 612, 618
        }
    }
}
